create table assignments (
	id INT,
	kursuse_id INT,
	ülesande_nimi TEXT,
	tähtaeg DATE
);
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (1, 776, 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', '5/20/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (2, 329, 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', '5/11/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (3, 97, 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', '12/21/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (4, 90, 'mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel', '6/14/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (5, 879, 'lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc', '4/19/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (6, 439, 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', '8/28/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (7, 591, 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient', '5/2/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (8, 359, 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus', '11/27/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (9, 239, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', '4/24/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (10, 67, 'enim blandit mi in porttitor pede justo eu massa donec dapibus duis at', '7/25/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (11, 973, 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula', '11/9/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (12, 848, 'ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem', '12/19/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (13, 268, 'convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget', '11/7/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (14, 767, 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', '4/28/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (15, 885, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea', '11/5/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (16, 878, 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu', '2/13/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (17, 704, 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede', '1/4/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (18, 138, 'proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget', '4/22/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (19, 153, 'eleifend luctus ultricies eu nibh quisque id justo sit amet', '4/5/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (20, 819, 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at', '2/17/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (21, 227, 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi', '3/13/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (22, 714, 'etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', '4/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (23, 182, 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', '12/4/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (24, 246, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac', '1/3/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (25, 572, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras', '4/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (26, 769, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', '8/17/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (27, 620, 'ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien', '11/7/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (28, 86, 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', '7/5/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (29, 497, 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl', '6/18/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (30, 842, 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', '10/19/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (31, 811, 'non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa', '11/18/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (32, 438, 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', '11/30/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (33, 200, 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus', '6/9/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (34, 112, 'id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet', '6/16/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (35, 262, 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus', '12/29/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (36, 625, 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis', '5/9/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (37, 790, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', '1/9/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (38, 980, 'duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat', '11/18/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (39, 938, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient', '7/16/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (40, 135, 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', '3/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (41, 193, 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', '12/18/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (42, 468, 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus', '8/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (43, 577, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum', '8/27/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (44, 191, 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl', '11/20/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (45, 743, 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est', '2/7/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (46, 925, 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac', '7/17/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (47, 228, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue', '5/2/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (48, 457, 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero', '12/1/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (49, 187, 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at', '11/24/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (50, 516, 'consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci', '10/9/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (51, 801, 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam', '1/26/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (52, 510, 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate', '1/9/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (53, 731, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', '10/24/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (54, 766, 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum', '5/14/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (55, 325, 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis', '10/15/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (56, 494, 'mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus', '1/15/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (57, 183, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', '8/23/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (58, 211, 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', '3/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (59, 411, 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis', '12/6/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (60, 646, 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis', '10/23/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (61, 96, 'nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget', '1/12/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (62, 600, 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo', '3/6/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (63, 118, 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus', '10/17/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (64, 273, 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel', '12/7/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (65, 971, 'morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac', '8/6/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (66, 553, 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia', '11/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (67, 802, 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo', '4/15/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (68, 228, 'in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis', '2/23/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (69, 35, 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', '2/14/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (70, 283, 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus', '11/9/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (71, 139, 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', '12/29/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (72, 856, 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', '1/25/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (73, 586, 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede', '7/29/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (74, 435, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus', '2/26/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (75, 58, 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', '4/18/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (76, 471, 'dui vel nisl duis ac nibh fusce lacus purus aliquet', '7/6/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (77, 232, 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non', '2/25/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (78, 3, 'ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', '5/4/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (79, 92, 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh', '6/4/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (80, 843, 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse', '11/30/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (81, 589, 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac', '10/16/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (82, 941, 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue', '8/30/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (83, 722, 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi', '2/21/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (84, 591, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum', '10/22/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (85, 624, 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate', '9/14/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (86, 953, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac', '6/6/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (87, 641, 'ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', '5/7/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (88, 865, 'nulla tellus in sagittis dui vel nisl duis ac nibh fusce', '11/14/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (89, 570, 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', '10/24/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (90, 775, 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam', '7/22/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (91, 578, 'non lectus aliquam sit amet diam in magna bibendum imperdiet', '10/26/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (92, 783, 'integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', '11/27/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (93, 961, 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in', '8/19/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (94, 69, 'eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis', '7/6/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (95, 313, 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat', '9/25/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (96, 81, 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis', '8/16/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (97, 27, 'elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy', '10/2/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (98, 574, 'eu nibh quisque id justo sit amet sapien dignissim vestibulum', '9/30/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (99, 623, 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla', '10/16/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (100, 434, 'nam dui proin leo odio porttitor id consequat in consequat ut', '4/18/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (101, 104, 'integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi', '5/6/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (102, 74, 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in', '1/19/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (103, 368, 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', '5/31/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (104, 336, 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id', '10/19/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (105, 197, 'semper rutrum nulla nunc purus phasellus in felis donec semper', '11/29/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (106, 847, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in', '3/27/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (107, 601, 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at', '10/24/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (108, 344, 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc', '12/25/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (109, 226, 'ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non', '8/29/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (110, 683, 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', '1/22/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (111, 135, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', '10/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (112, 438, 'consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante', '1/5/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (113, 163, 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam', '6/27/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (114, 685, 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', '7/3/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (115, 358, 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', '10/22/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (116, 925, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', '10/9/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (117, 995, 'in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque', '3/2/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (118, 549, 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel', '4/29/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (119, 930, 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', '8/14/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (120, 782, 'mauris enim leo rhoncus sed vestibulum sit amet cursus id', '9/28/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (121, 985, 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh', '6/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (122, 300, 'in est risus auctor sed tristique in tempus sit amet sem', '11/17/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (123, 131, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel', '7/24/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (124, 465, 'non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui', '10/3/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (125, 760, 'vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', '6/1/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (126, 817, 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', '1/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (127, 152, 'mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', '4/21/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (128, 899, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac', '2/14/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (129, 366, 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio', '4/18/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (130, 262, 'ante ipsum primis in faucibus orci luctus et ultrices posuere', '9/20/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (131, 324, 'sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci', '11/4/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (132, 626, 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat', '5/5/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (133, 772, 'ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non', '3/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (134, 52, 'libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc', '9/29/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (135, 791, 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', '10/18/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (136, 967, 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer', '12/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (137, 362, 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit', '10/28/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (138, 408, 'augue a suscipit nulla elit ac nulla sed vel enim', '2/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (139, 176, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', '8/3/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (140, 369, 'est et tempus semper est quam pharetra magna ac consequat', '1/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (141, 482, 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce', '5/28/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (142, 623, 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia', '1/26/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (143, 805, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', '11/11/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (144, 319, 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede', '3/24/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (145, 389, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', '8/27/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (146, 813, 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse', '5/31/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (147, 151, 'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', '9/11/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (148, 44, 'pretium quis lectus suspendisse potenti in eleifend quam a odio in', '4/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (149, 522, 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla', '2/22/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (150, 768, 'ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', '3/7/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (151, 947, 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec', '5/16/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (152, 495, 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', '10/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (153, 731, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit', '10/5/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (154, 312, 'leo odio porttitor id consequat in consequat ut nulla sed accumsan', '5/13/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (155, 30, 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit', '3/2/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (156, 437, 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in', '1/5/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (157, 453, 'venenatis turpis enim blandit mi in porttitor pede justo eu', '7/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (158, 951, 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', '8/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (159, 181, 'tempus sit amet sem fusce consequat nulla nisl nunc nisl', '1/15/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (160, 940, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', '12/15/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (161, 251, 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', '10/20/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (162, 301, 'felis eu sapien cursus vestibulum proin eu mi nulla ac', '10/16/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (163, 930, 'volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', '2/12/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (164, 60, 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium', '7/23/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (165, 196, 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '8/23/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (166, 998, 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque', '8/23/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (167, 128, 'nec dui luctus rutrum nulla tellus in sagittis dui vel', '11/8/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (168, 382, 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu', '11/27/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (169, 460, 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', '7/24/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (170, 987, 'in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper', '12/1/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (171, 473, 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices', '6/25/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (172, 332, 'nam dui proin leo odio porttitor id consequat in consequat ut nulla sed', '8/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (173, 699, 'lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl', '5/15/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (174, 493, 'velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', '7/5/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (175, 276, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis', '1/11/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (176, 672, 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer', '6/28/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (177, 444, 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla', '7/7/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (178, 792, 'convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus', '5/21/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (179, 675, 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer', '8/13/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (180, 107, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget', '11/2/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (181, 890, 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', '6/11/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (182, 67, 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat', '12/18/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (183, 249, 'vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', '1/15/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (184, 712, 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc', '3/3/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (185, 753, 'eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse', '1/6/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (186, 997, 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla', '6/20/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (187, 640, 'ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus', '8/21/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (188, 416, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat', '9/25/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (189, 221, 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie', '2/10/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (190, 526, 'leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', '9/23/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (191, 771, 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget', '8/22/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (192, 924, 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', '2/4/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (193, 240, 'porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum', '10/31/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (194, 522, 'pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', '8/27/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (195, 817, 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', '7/20/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (196, 642, 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non', '5/11/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (197, 489, 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in', '4/14/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (198, 451, 'posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit', '8/27/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (199, 245, 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est', '5/1/2022');
insert into assignments (id, kursuse_id, ülesande_nimi, tähtaeg) values (200, 771, 'elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium', '4/19/2022');
